### ISSUE TITLE
redeclared; use <class-extension> instead.

### ISSUE THREAD

**Issue by marvi** [tingraldi/SwiftScripting#1]
Hi, thanks for this project.

I'm trying to make a scripting framework for Wirecast from Telestream. It seems they have done something wrong for their AppleScript dictionary. They reuse `application` and `document`. I tried changing the sdef to use `<class-extension>`. The .h file seems now to be generated ok with sdp. 

But when I try to emit the Swift code it fails with this error:

```
./sbhc.py Wirecast.h
Traceback (most recent call last):
  File "./sbhc.py", line 214, in <module>
    main(sys.argv[1])
  File "./sbhc.py", line 209, in main
    header_processor.emit_swift()
  File "./sbhc.py", line 203, in emit_swift
    self.emit_protocol(child)
  File "./sbhc.py", line 159, in emit_protocol
    if child.kind == CursorKind.OBJC_SUPER_CLASS_REF][0]
IndexError: list index out of range
```

Is it the inheritance that breaks the Swift generation?

SDEF file: https://gist.github.com/marvi/bb3f6b0cd8ff57d8d745

**Comment by nemesit** [comment]
I get that error too with mail.app

**Comment by tingraldi** [comment]
My apologies for the late response here.

Another user has encountered this issue. I've not yet been able to reproduce the problem. I'll look into this further.

**Comment by tingraldi** [comment]
I've reproduced the issue on a system with Xcode 6.0.1 installed and updated the sbhc.py script on master to resolve the issue. The update uses a different approach than before to determine the superclass for a given interface declaration.

**Comment by tingraldi** [comment]
Fixed as of https://github.com/tingraldi/SwiftScripting/commit/f968c31933c1f959e4626c48babf5570819ea418

**Comment by marvi** [comment]
Thanks for looking into this. I will try it and let you know.
