### ISSUE TITLE
Wrong types of attributes and missing function return values

### ISSUE THREAD

**Issue by martomi** [tingraldi/SwiftScripting#10]
I've noticed an issue with the types generated by the script. Here's how to reproduce the issue:

1) sdef /Applications/Safari.app > Safari.sdef
2) sdp -fh --basename Safari Safari.sdef
3) sbhc.py Safari.h

Now looking at Safari.swift, the types of attributes are not the same as in the header file. All functions seem to lack return values and attributes are quite often of type Int instead of their actual type.

I'm running Python 2.7.10 on MacOS Version 10.12.1

**Comment by martomi** [comment]
Seems like I had an old version of the Xcode command line tools!
It anyone is having the same problem, just run `xcode-select --install`

Thanks for writing this utility, it's super useful! 👍

**Comment by tingraldi** [comment]
Thank you for your interest in SwiftScripting.

It appears that you had the same issue as what was reported here: https://github.com/tingraldi/SwiftScripting/issues/7. I need to make the statement regarding installation of the command line tools more prominent in the README. It's easy to miss that.
