### ISSUE TITLE
Swift 4: var running error 

### ISSUE THREAD

**Issue by marc-medley** [tingraldi/SwiftScripting#12]
FYI: Swift 4 produces a compile time error for

``` swift
var running: Bool { @objc(isRunning) get }
``` 

> ERROR: Unavailable var 'running' was used to satisfy a requirement of protocol 'SBApplicationProtocol'

Here is one possible alternative that compiles and runs OK for me in Xcode 9, Swift 4 beta 6:

``` swift
@objc optional var isRunning: Bool { get }
```

Here's another alternative, without using `@objc optional`, which is also currently running OK for me on macOS 10.12,  Xcode 9 beta 6, Swift 4:

``` swift 
@objc
public protocol SBApplicationProtocol: SBObjectProtocol {
    func activate()
    var delegate: SBApplicationDelegate! { get set }
    var isRunning: Bool { get }
}
```

**Comment by tingraldi** [comment]
@marc-medley Thanks for the heads-up. I've yet to look at a Swift 4 update to SwiftScripting. I'll keep this in mind.

**Comment by tingraldi** [comment]
I just pushed an update for Swift 4. Please give it a try and see if it resolves this issue.
