### ISSUE TITLE
Incorrect types on High Sierra

### ISSUE THREAD

**Issue by sahayman** [tingraldi/SwiftScripting#13]
Thank you for this.  Tried running the scripts on 10.13.1 Beta (17B46a)
After doing this

sdef /Applications/Safari.app > Safari.sdef
sdp -fh --basename Safari Safari.sdef
./sbhc.py Safari.h
./sbsc.py Safari.sdef

the resulting Safari.swift seems to be mistyping many things. it produces this (an excerpt) - note that '**name**' is an Int, for instance, and the **documents** function isn't returning anything

// MARK: SafariApplication
@objc public protocol SafariApplication: SBApplicationProtocol {
    **@objc optional func documents()**
    @objc optional func windows()
    **@objc optional var name: Int { get } // The name of the application.**
    @objc optional var frontmost: Int { get } // Is this the active application?
    @objc optional var version: Int { get } // The version number of the application.
    @objc optional func `open`(_ x: Any!) -> Any // Open a document.
    @objc optional func print(_ x: Any!, withProperties: Any!, printDialog: Any!) // Print a document.
    @objc optional func quitSaving(_ saving: SafariSaveOptions) // Quit the application.
    @objc optional func exists(_ x: Any!) // Verify that an object exists.
    @objc optional func addReadingListItem(_ x: Any!, andPreviewText: Any!, withTitle: Any!) // Add a new Reading List item with the given URL. Allows a custom title and preview text to be specified.
    @objc optional func doJavaScript(_ x: Any!, in in_: Any!) -> Any // Applies a string of JavaScript code to a document.
    @objc optional func emailContentsOf(_ of: Any!) // Emails the contents of a tab.
    @objc optional func searchTheWebIn(_ in_: Any!, for for_: Any!) // Searches the web using Safari's current search provider.
    @objc optional func showBookmarks() // Shows Safari's bookmarks.
}

Compared that to the example project here https://github.com/brightdigit/jURLnal which I think was built before 10.13, and in that one Safari.swift contains this ('name' is a String and documents() returns an SBElementArray which seems better

// MARK: SafariApplication
@objc public protocol SafariApplication: SBApplicationProtocol {
    **@objc optional func documents() -> SBElementArray**
    @objc optional func windows() -> SBElementArray
    **@objc optional var name: String { get } // The name of the application.**
    @objc optional var frontmost: Bool { get } // Is this the active application?
    @objc optional var version: String { get } // The version number of the application.
    @objc optional func `open`(_ x: Any!) -> Any // Open a document.
    @objc optional func print(_ x: Any!, withProperties: [AnyHashable : Any]!, printDialog: Bool) // Print a document.
    @objc optional func quitSaving(_ saving: SafariSaveOptions) // Quit the application.
    @objc optional func exists(_ x: Any!) -> Bool // Verify that an object exists.
    @objc optional func addReadingListItem(_ x: String!, andPreviewText: String!, withTitle: String!) // Add a new Reading List item with the given URL. Allows a custom title and preview text to be specified.
    @objc optional func doJavaScript(_ x: String!, in in_: Any!) -> Any // Applies a string of JavaScript code to a document.
    @objc optional func emailContentsOf(_ of: Any!) // Emails the contents of a tab.
    @objc optional func searchTheWebIn(_ in_: Any!, for for_: String!) // Searches the web using Safari's current search provider.
    @objc optional func showBookmarks() // Shows Safari's bookmarks.
}

**Comment by tingraldi** [comment]
Thank you for filing an issue.

This issue is not specific to High Sierra (see #7). The Xcode command line tools need to be installed for the sbhc.py script to work properly. You can issue the command `xcode-select --install` in a Terminal window to initiate installation of the command line tools.

**Comment by sahayman** [comment]
Thank you - I will try that.  Isn't installing the command line tools kind of redundant these days since everything is already buried inside the Xcode.app bundle?
