### ISSUE TITLE
xcode create lots of fails when building

### ISSUE THREAD

**Issue by fuwjigfuwjig** [tingraldi/SwiftScripting#14]
Hi, 
I want to work on some automation task on adobe illustrator application. after creating xcode project , I import 2 swift header files into project. in order to have project indexed I try to build at least once. yet the imported swift files cause lots of failure.
I use XCode 9 and both swift 4 and 3 version. xcode command line tool updated as explained on readme file also python binding installed.
regards

Showing Recent Issues
/Users/illustraterico/illustraterico/headers/Illustrator.swift:788:10: Expected pattern

/Users/illustraterico/illustraterico/headers/Illustrator.swift:788:10: Keyword 'subscript' cannot be used as an identifier here

/Users/illustraterico/illustraterico/headers/Illustrator.swift:788:9: Consecutive declarations on a line must be separated by ';'

/Users/illustraterico/illustraterico/headers/Illustrator.swift:788:20: Expected '(' for subscript parameters

/Users/illustraterico/illustraterico/headers/Illustrator.swift:794:10: Expected pattern

/Users/illustraterico/illustraterico/headers/Illustrator.swift:794:10: Keyword 'default' cannot be used as an identifier here

/Users/illustraterico/illustraterico/headers/Illustrator.swift:794:9: Consecutive declarations on a line must be separated by ';'

/Users/illustraterico/illustraterico/headers/Illustrator.swift:794:10: Expected declaration

/Users/illustraterico/illustraterico/headers/Illustrator.swift:797:10: Expected pattern

/Users/illustraterico/illustraterico/headers/Illustrator.swift:797:10: Keyword 'subscript' cannot be used as an identifier here

/Users/illustraterico/illustraterico/headers/Illustrator.swift:797:9: Consecutive declarations on a line must be separated by ';'

/Users/illustraterico/illustraterico/headers/Illustrator.swift:797:20: Expected '(' for subscript parameters

/Users/illustraterico/illustraterico/headers/Illustrator.swift:803:10: Expected pattern

/Users/illustraterico/illustraterico/headers/Illustrator.swift:803:10: Keyword 'default' cannot be used as an identifier here

/Users/illustraterico/illustraterico/headers/Illustrator.swift:803:9: Consecutive declarations on a line must be separated by ';'

**Comment by tingraldi** [comment]
Thank you for using SwiftScripting.

The main issue was that the `sbhc.py` script wasn't handling Swift keywords properly. I've updated the script to address this issue. Beyond that, there were two unrelated issues in the Illustrator SDEF that I manually addressed.

I've added a complete Illustrator framework to the project. Please give it a try and see how it goes. Here's a minimal script that will launch Illustrator (provided that the Illustrator and ScriptingUtilities frameworks have been built and installed.)

```swift
#!/usr/bin/xcrun swift -F /Library/Frameworks

import ScriptingUtilities
import IllustratorScripting

let app = application(name: "Adobe Illustrator", locations: ["/Applications/Adobe Illustrator CC 2018"]) as! IllustratorApplication

app.activate()
```

**Comment by fuwjigfuwjig** [comment]
Thank you for your solution. it's been working now. I will check whether indesign also works.

**Comment by tingraldi** [comment]
You're welcome. I'm glad to hear that your issue has been resolved.
