### ISSUE TITLE
Swift 3

### ISSUE THREAD

**Issue by west0r** [tingraldi/SwiftScripting#8]
Please update to swift 3

**Comment by tingraldi** [comment]
I plan to update the project for Swift 3 soon. Most likely in the next couple of weeks, barring unforeseen major incompatibilities.

**Comment by tingraldi** [comment]
The sbhc.py script has been tweaked for Swift 3 compatibility. Still compatible with Swift 2.x as well. All sample frameworks have been updated for Swift 2.x/3.x.
